server:
  port: 8020
spring:
  application:
    name: orderServer-nacos
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: order
        password: order
        namespace: public
#        ephemeral: false #设置为永久实例，即使该服务宕机也不会在nacos注册表中删除
        service: orderservice
      username: nacos
      password: nacos
