server:
  port: 8041
spring:
  application:
    name: product-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8801
        discovery:
          username: order
          password: order
          namespace: public
          service: product-service